### ISSUE TITLE
Use another api

### ISSUE THREAD

**Issue by DannyDan0167** [Awardxz/quizzizV2#1]
Why can't you use schoolcheats or cheatnetwork's API?

**Comment by Awardxz** [comment]
> Why can't you use schoolcheats or cheatnetwork's API?

U can use it, for cheatnetwork's api you just need to log in use it once and copy your personal request then implement it into the fetch in the script. To why i didn't do it is cause i don't have time to improve it

I was also going to create my own API but then i discontinued the project due to being bored from it

**Comment by Awardxz** [comment]
If you want to create your own api one way you can achieve is with quizzizJS i think its called you can do it with that . Then just implement the api. It's easy as that.

**Comment by DannyDan0167** [comment]
Ok

**Comment by DannyDan0167** [comment]
Thank you

**Comment by Awardxz** [comment]
No problem - i'll be closing this issue now 👍
